class PIPELINE_STEPS:
    ALIGN = "align"
    NAPS_ALIGNED = "naps_aligned"
    NAPS = "naps"
    CONTRASTIVE_NAPS = "contrastive_naps"
    TOPOMAP_LAYOUT = "topomap_layout"
    TOPOMAP_LAYOUT_CONTRASTIVE = "topomap_layout_contrastive"
    TOPOMAP_ACTIVATIONS = "topomap_activations"
    TOPOMAP_ACTIVATIONS_CONTRASTIVE = "topomap_activations_contrastive"
    TOPOMAP_PLOTS = "topomap_plots"
